# Generated by Django 3.1.7 on 2021-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicnicArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME_PICNIC', models.CharField(max_length=100, verbose_name='Наименование места для пикника')),
                ('ADDRESS_LANDMARK', models.CharField(default='', max_length=100, verbose_name='Адресный ориентир')),
                ('SERVICE_PROVIDER', models.CharField(default='', max_length=100, verbose_name='Обслуживающая организация')),
                ('PHONE', models.CharField(default='', max_length=100, verbose_name='Телефон')),
                ('GEOOBJECT_NAME', models.CharField(default='', max_length=100, verbose_name='Наименование геобъекта')),
                ('GEOCOORD', models.CharField(default='', max_length=100, verbose_name='Геокоординаты')),
                ('THE_PHOTO', models.ImageField(upload_to='picnic_area/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Зона для пикника',
                'verbose_name_plural': 'Зоны для пикника',
            },
        ),
    ]
