# Generated by Django 3.1.7 on 2021-03-01 10:45

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('picnic_area_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picnicarea',
            name='DATE_UPDATE',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='picnicarea',
            name='DESCRIPTION',
            field=models.TextField(default='Описание отсутствует...', verbose_name='Описание'),
        ),
    ]
