# Generated by Django 3.1.7 on 2021-03-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic_area_app', '0003_auto_20210301_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picnicarea',
            name='DATE_UPDATE',
            field=models.DateTimeField(blank=True, default='01-03-2021 15:51'),
        ),
    ]
