# Generated by Django 3.1.7 on 2021-03-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic_area_app', '0005_auto_20210301_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picnicarea',
            name='DATE_UPDATE',
            field=models.DateTimeField(blank=True, default='2021-03-01 16:58'),
        ),
        migrations.AlterField(
            model_name='picnicarea',
            name='THE_PHOTO',
            field=models.ImageField(default='picnic_area/base_image.jpg', upload_to='picnic_area/', verbose_name='Фото'),
        ),
    ]
