# Generated by Django 3.1.7 on 2021-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic_area_app', '0008_auto_20210311_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='', upload_to='categories/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='picnicarea',
            name='DATE_UPDATE',
            field=models.DateTimeField(blank=True, default='2021-03-11 10:37'),
        ),
    ]
