# Generated by Django 3.1.7 on 2021-03-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic_area_app', '0009_auto_20210311_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='picnicarea',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='picnicarea',
            name='DATE_UPDATE',
            field=models.DateTimeField(blank=True, default='2021-03-11 12:07'),
        ),
    ]
