# Generated by Django 3.1.7 on 2021-03-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic_area_app', '0011_auto_20210311_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='picnicarea',
            name='DATA_FROM_OD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picnicarea',
            name='DATE_UPDATE',
            field=models.DateTimeField(blank=True, default='2021-03-11 16:25'),
        ),
    ]
